all:
  hosts:
    lms-demo-oc.vm2.elan.codes:
      # for repository:
      opencast_version_major: 13
      # for tarball:
      version: 15-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
    ansible_ssh_user: ansible
    studip_uri: https://lms-demo-studip.vm2.elan.codes

