stage_deploy:
  variables:
    NVM_DIR: "/usr/local/nvm"
  image: forestryengland/php-npm-composer
  artifacts:
    paths:
      - build/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apt-get update
    - apt-get install zip unzip curl
    - export
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    - nvm install stable
    - npm run zip
  script:
    - "curl -k -T `ls build/*.zip` -u \"${NEXTCLOUD_SHARE_ID}:${NEXTCLOUD_SHARE_PW}\" -H 'X-Requested-With: XMLHttpRequest' $NEXTCLOUD_SHARE_URL/Opencast-`date '+%Y-%m-%d'`.zip"

