---

- name: install nginx
  package:
    name: nginx
    state: present

- name: install le dependencies
  package:
    name: ["certbot", "python3-certbot-apache"]
    state: present

- name: create ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: configure nginx mime types
  copy:
    src: mime.types
    dest: /etc/nginx/mime.types
    owner: root
    group: root
    mode: '0644'

- name: create diffie hellman ephemeral parameters for nginx
  community.crypto.openssl_dhparam:
    path: /etc/nginx/ssl/dhparam.pem
    size: 2048
    owner: root
    group: root
    mode: '0640'

- name: configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0640
  notify: reload nginx

- name: install selinux config libs
  package:
    name: python3-libsemanage
  when: >
    ansible_os_family == 'RedHat'
    and ansible_distribution_major_version >= '8'

- name: allow httpd to act as reverse proxy
  become: true
  seboolean:
    name: httpd_can_network_relay
    state: true
    persistent: true
  when: >
    ansible_distribution == 'CentOS'
    or ansible_distribution == 'RedHat'
    or ansible_distribution == 'Scientific'

- name: start and enable nginx
  service:
    name: nginx
    enabled: true
    state: started
